name: Push Gem to PackageCloud

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  push_gem:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build Gem
        run: bundle exec rake build

      - name: Install PackageCloud CLI
        run: |
          gem install package_cloud

      - name: Set up PackageCloud CLI
        run: |
          echo "machine packagecloud.io login token ${{ secrets.PACKAGECLOUD_TOKEN }}" >> ~/.netrc
          chmod 600 ~/.netrc

      - name: Push Gem to PackageCloud
        run: |
            gem_file=$(ls pkg/*.gem)
            package_cloud push ${{ secrets.PACKAGECLOUD_USERNAME }}/${{ secrets.PACKAGECLOUD_REPOSITORY }} $gem_file